server:
  port: 56010

spring:
  application:
    name: nacos-restful-provider #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.200:8848  #服务发现中心地址
        namespace: 55aebc57-547f-46a1-ba72-733fe17b9204 # 命名空间
